name: Build and Test - Local

#
# This workflow uses the actions/setup-java action to provide a targeted version of Java that
# the project is compiled against.
#
# The version of Maven that is used is whatever version is present in the hosted runner environment.
#
# The maven execution injects Artifactory configuration details via the settings.xml file that is provided
# as part of the sources. These are stored as Secrets and can be provided at a Repository or Organization level.
#

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test

    runs-on: ubuntu-20.04

    steps:
      - name: Set up Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk

      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Cache Maven Repository
        id: cache-maven-repository
        uses: actions/cache@v2
        with:
          path: .m2/repository
          key: ${{ runner.os }}-build-${{ hashFiles('**/pom.xml') }}

      - name: Did we get a cache hit
        run: echo "Cache Hit? ${{ steps.cache-maven-repository.outputs.cache-hit }}"

      - name: Maven Build and Test
        env:
          GITHUB_TEST_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn test --batch-mode --settings ./settings.xml \
            -Dartifactory.server.mirror.url=${{ secrets.ARTIFACTORY_SERVER_MIRROR_URL }} \
            -Dartifactory.user.name=${{ secrets.ARTIFACTORY_USERNAME }} \
            -Dartifactory.user.password=${{ secrets.ARTIFACTORY_PASSWORD }}
        shell: bash
      
