name: Build and Test

on:
  push:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test

    runs-on: ubuntu-20.04

    container:
      image: maven:3.6.3-jdk-11-slim
      volumes:
        - ./.m2:/root/.m2
        - ./settings.xml:/root/.m2/settings.xml
        - ./:/src
      options: -w /src

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Maven Build and Test
        run: mvn test --batch-mode -Dartifactory.server.mirror.url=${{ secrets.ARTIFACTORY_SERVER_MIRROR_URL }} - Dartifactory.user.name=${{ secrets.ARTIFACTORY_USERNAME }} -Dartifactory.user.password=${{ secrets.ARTIFACTORY_PASSWORD }}

      #TODO add caching